In [16]:
import nashpy as nash
import numpy as np

A = np.array([[5,1,4,4], [2,0,3,1], [3,0,4,1], [5,2,0,0], [1,1,6,4]])
B = np.array([[1,2,0,4,6], [0,0,5,0,6], [3,5,3,2,0], [0,5,5,5,5]])
rps = nash.Game(A, B.T)
print(rps)

Bi matrix game with payoff matrices:

Row player:
[[5 1 4 4]
 [2 0 3 1]
 [3 0 4 1]
 [5 2 0 0]
 [1 1 6 4]]

Column player:
[[1 0 3 0]
 [2 0 5 5]
 [0 5 3 5]
 [4 0 2 5]
 [6 6 0 5]]


In [17]:
list(rps.support_enumeration())

[(array([0.75, 0.  , 0.  , 0.  , 0.25]),
  array([0.33333333, 0.        , 0.66666667, 0.        ]))]

In [13]:
from scipy.optimize import linprog

A = -np.array([[1,0,3,0,-1], [2,0,5,5,-1], [0,5,3,5,-1], [4,0,2,5,-1], [6,6,0,5,-1], [-1,-1,-1,-1,0], [1,1,1,1,0]])
b = [0, 0, 0, 0, 0, -1, 1]
c = [0, 0, 0, 0, 1]
linprog(c, A_ub=A, b_ub=b)

       message: The problem is infeasible. (HiGHS Status 8: model_status is Infeasible; primal_status is None)
       success: False
        status: 2
           fun: None
             x: None
           nit: 0
         lower:  residual: None
                marginals: None
         upper:  residual: None
                marginals: None
         eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None

In [14]:
A = np.array([[5, 1, 4, 4, -1], [2, 0, 3, 1, -1], [3, 0, 4, 1, -1], [5, 2, 0, 0, -1], [1, 1, 6, 4, -1], [1, 1, 1, 1, 0], [-1, -1, -1, -1, 0]])
b = [0, 0, 0, 0, 0, 1, -1]
c = [0, 0, 0, 0, 1]
linprog(c, A_ub=A, b_ub=b)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 1.6
              x: [ 0.000e+00  8.000e-01  0.000e+00  2.000e-01  1.600e+00]
            nit: 3
          lower:  residual: [ 0.000e+00  8.000e-01  0.000e+00  2.000e-01
                              1.600e+00]
                 marginals: [ 1.800e+00  0.000e+00  8.000e-01  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.400e+00  1.400e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-0.000e+00 -0.000e+00 -0.000e+00 -6.000e-01
                             -4.000e-